###
#
# cd_dev.yml
#
# Config data for the DEV environment
#
###

url: 'http://dev.enrg.bloxico.com/auth'
api_url: 'http://dev-api.enrg.bloxico.com/'
api_user: 'qa-partner'
api_pass: 'djlxb2vz1hnvhl46'  
