###
#
# td_dev.yml
#
# TD (Test Data) test data for the DEV environment
#
###

users:
  qa_user_1:
    email: qatesting97@cliptik.net
    password: Isto123!
    reapetPassword: Isto123!
    country: Serbia
    city: Belgrade
    nickname: Tests

  qa_user_2:
    email: xogemov@mail-share.com
    password: Isto123!

  qa_user_3:
    email: qatestinginvalidmail
    password: Isto123!
    reapetPassword: Isto123!
    country: Serbia
    city: BGD
    nickname: invalidMail