###
#
# td_prod.yml
#
# TD (Test Data) test data for the PROD environment
#
###

users:
  user_1:
    email: test1@cliptik.net
    password: Isto123!
    reapetPassword: Isto123!
    country: Serbia
    city: Belgrade
    nickname: Tests

  user_2:
    email: 
    password: 