###
#
# td_stage.yml
#
# TD (Test Data) test data for the Stage environment
#
###

users:
  qa_user_1:
    email: dimitrije.dragasevic@gmail.com
    password: dimitrije1994

  qa_user_2:
    email: 
    password: 
