###
#
# td_stage.yml
#
# TD (Test Data) test data for the STAGE environment
#
###

users:
  qa_user_1:
    email: test1@cliptik.net
    password: Isto123!
    reapetPassword: Isto123!
    country: Serbia
    city: Belgrade
    nickname: Tests

  qa_user_2:
    email: sekula@radili.com
    password: Isto123!
